[deploy]
startCommand = "gunicorn IBH.wsgi --workers 4"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.worker]
startCommand = "celery -A IBH worker -l info -P gevent"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10